### Add sheets
POST http://localhost:8080/api/sheets
Content-Type: application/json

{
  "number": "123",
  "rate": 50,
  "teamName": "ZODK",
  "monitorName": "Paweł",
  "body": "Średnio",
  "proces": "POŻYCZKA"
}

### Delete sheets
DELETE http://localhost:8080/api/sheets/3

### Update sheets
PUT http://localhost:8080/api/sheets/123
Content-Type: application/json

{
  "number": "123",
  "proces": "Keto",
  "rate": 5,
  "body": "Non possumus!",
  "edited": true,
  "note": {
    "id": 1,
    "comment": "brak akceptacji"
  }
}



### Get Sheets
GET http://localhost:8080/api/sheets/highest
