### Add sheets
POST http://localhost:8080/api/sheets
Content-Type: application/json

{
  "number": "34543",
  "proces": "POŻYCZKA",
  "body": "Miejsce na komentarz",
  "rate": 100,
  "monitorName": "Paweł",
  "teamName": "ZODK"
}

### Update sheets
PUT http://localhost:8080/api/sheets/34543
Content-Type: application/json

{
  "number": "34543",
  "proces": "Depo",
  "rate": 95,
  "Body": "Non possumus!",
  "noted": true
}
