### Add teams
POST http://localhost:8080/api/teams
Content-Type: application/json

{
  "name": "ZORRO",
  "department": "zOKE",
  "monitor": {
    "id": 1,
    "personalNumber": "string",
    "name": "string"
  }
}